services:
  # Combined Frontend and Backend Service
  - type: web
    name: speedtest-app
    env: node
    plan: free
    buildCommand: npm run build:all
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: ENABLE_CLUSTER
        value: "true"
      - key: RATE_LIMIT_WINDOW_MS
        value: "60000"
      - key: RATE_LIMIT_MAX_REQUESTS
        value: "500"
      - key: KEEP_ALIVE_TIMEOUT
        value: "65000"
      - key: HEADERS_TIMEOUT
        value: "66000"