name = "speed-test-app"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Pages configuration
pages_build_output_dir = "project/dist"
pages_functions_dir = "functions"

[env.production]
name = "speed-test-app"

[env.preview]
name = "speed-test-app-preview"

# Environment variables
[vars]
NODE_ENV = "production"
RATE_LIMIT_WINDOW_MS = "60000"
RATE_LIMIT_MAX_REQUESTS = "500"

# Durable Objects for WebSocket state management
[[durable_objects.bindings]]
name = "WEBSOCKET_STATE"
class_name = "WebSocketState"
script_name = "websocket-worker"

# KV namespace for storing test results (optional)
[[kv_namespaces]]
binding = "SPEED_TEST_RESULTS"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"