name = "websocket-worker"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]
main = "functions/websocket.js"

[[durable_objects.bindings]]
name = "WEBSOCKET_STATE"
class_name = "WebSocketState"

[env.production]
name = "websocket-worker"

[env.preview]
name = "websocket-worker-preview"